version: '2.0'

networks:
  networkwifi: 
    ipam:
      config:
        - subnet: 10.0.10.0/24
services:
  db:
    image: mysql:5.7
    networks:
      - networkwifi
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: network_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql-data:/var/lib/mysql
  backend:
    build: .
    ports:
      - 8085:8085
    networks:
      - networkwifi
    depends_on:
      - db